# Site settings
title: UkokuGemini's Blog
SEOTitle: UkokuGemini's Blog | UkokuGemini's Blog
header-img: img/WebSite/BG.jpg
email: Ukoku@live.cn
description: "UkokuGemini Just UkokuGemini."
keyword: "UkokuGemini"
url: "http://UkokuGemini.github.io"          
baseurl: "."    
github_repo: "https://github.com/UkokuGemini/UkokuGemini.github.io.git" 
version: "[1.1.6]"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "UkokuGemini Just UkokuGemini."
sidebar-avatar: /img/WebSite/Mine.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: true
github_username:    UkokuGemini

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
exclude: ["node_modules","README.md"]
plugins: [jekyll-paginate]
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important

#浏览器类型 
UA: true

# Friends
friends: [
    {
        title: "sunshineyg",
        pic: "https://avatars.githubusercontent.com/u/58005045?v=4",
        href: "https://github.com/sunshineyg"
    },
    {
        title: "psy",
        pic: "/img/Icon/UnUser.png",
        href: ""
    },
    #{
    #    title: "大庭叶藏",
    #    pic: "/img/Icon/qzone.png",
    #    href: "https://user.qzone.qq.com/857558572"
    #},
    #{
    #    title: "筑梦踏实",
    #    pic: "/img/Icon/qzone.png",
    #    href: "https://user.qzone.qq.com/563088446"
    #},
    #{
    #    title: "可可",
    #    pic: "/img/Icon/qzone.png",
    #   href: "https://user.qzone.qq.com/530041647"
    #},
    {
        title: "404",
        pic: "/img/Icon/404.png",
        href: "https://ukokugemini.github.io/404"
    },
    {
        title: "Offline",
        pic: "/img/Icon/Offline.png",
        href: "https://ukokugemini.github.io/offline"
    }
]
# BgmSeverPath: "http://47.96.176.56:8089/github.io.sever/music.pack"
BgmSources: [
    #{
    #    name: "Just For You",
    #    artist: "Giovanni Marradi",
    #    src: "/music/JustForYou.mp3"
    #},
    {
        name: "1时间",
        artist: "ハンバート_ハンバート",
        src: "/music/1时间.mp3",
        cover: "/music/1时间.png"
    }
]
